/**
 * Thumbnail variants generated by the backend ImageProcessingService.
 * Keep in sync with `App\Services\ImageProcessingService::BANNER_SIZES`
 * and `SQUARE_SIZES`.
 */
export type ThumbnailSize = 'thumb' | 'small' | 'medium' | 'large';

/**
 * Convert an original-image URL into its server-side thumbnail variant.
 *
 *   /storage/events/banners/abc.webp
 *   → /storage/events/banners/thumbnails/medium/abc.webp
 *
 * Pass-through for `null`, external URLs (http/https), and data URIs so we
 * don't accidentally rewrite something we don't own.
 */
export function thumbnailUrl(
    originalUrl: string | null | undefined,
    size: ThumbnailSize,
): string | null {
    if (!originalUrl) {
        return null;
    }

    if (
        originalUrl.startsWith('http://') ||
        originalUrl.startsWith('https://') ||
        originalUrl.startsWith('data:')
    ) {
        return originalUrl;
    }

    const slash = originalUrl.lastIndexOf('/');

    if (slash === -1) {
        return originalUrl;
    }

    const directory = originalUrl.slice(0, slash);
    const filename = originalUrl.slice(slash + 1);

    return `${directory}/thumbnails/${size}/${filename}`;
}
